In [1]:
#importing the relevant packages - check which ones are necessary.

from pathlib import Path
import pandas as pd
import os
import glob
import numpy as np
#import gc

In [2]:
data_path = Path("data_files")

In [3]:
#inspecting the data
parquet_files = sorted(data_path.glob("*.parquet"))

print(f"Found {len(parquet_files)} parquet files.\n" + "="*50)
for path in parquet_files:
    print(path)

Found 8 parquet files.
==================================================
data_files\amazon_books_metadata.parquet
data_files\Books_rating.parquet
data_files\bx_books_metadata.parquet
data_files\bx_ratings.parquet
data_files\bx_users.parquet
data_files\goodreads_book_id_map.parquet
data_files\goodreads_books_part_000.parquet
data_files\goodreads_user_id_map.parquet

In [4]:
inspect_dict = {}

for filepath in sorted(parquet_files):
    filename = os.path.basename(filepath)
    # Read metadata/schema efficiently without loading entire huge files into memory
    df = pd.read_parquet(filepath)

    inspect_dict[filename] = df

    print(f"\n📂 FILE: {filename}")
    print(f"   Shape: {df.shape[0]:,} rows x {df.shape[1]} columns")
    print(f"   Columns: {list(df.columns)}")
    print("\n   Sample Data (First 10 rows):")
    display(df.head(10))
    print("-" * 50)

📂 FILE: amazon_books_metadata.parquet
   Shape: 200,885 rows x 6 columns
   Columns: ['Title', 'description', 'authors', 'categories', 'ratingsCount', 'clean_title']

   Sample Data (First 10 rows):

,Title,description,authors,categories,ratingsCount,clean_title
0,Its Only Art If Its Well Hung!,<NA>,['Julie Strain'],Comics & Graphic Novels,0,its only art if its well hung
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],Biography & Autobiography,0,dr seuss american icon
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],Religion,0,wonderful worship in smaller churches
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],Fiction,0,whispers of the wicked saints
4,"Nation Dance: Religion, Identity and Cultural ...",<NA>,['Edward Long'],<NA>,0,nation dance religion identity and cultural di...
5,The Church of Christ: A Biblical Ecclesiology ...,In The Church of Christ: A Biblical Ecclesiolo...,['Everett Ferguson'],Religion,5,the church of christ a biblical ecclesiology f...
6,The Overbury affair (Avon),<NA>,['Miriam Allen De Ford'],<NA>,0,the overbury affair
7,A Walk in the Woods: a Play in Two Acts,<NA>,['Lee Blessing'],<NA>,3,a walk in the woods a play in two acts
8,Saint Hyacinth of Poland,The story for children 10 and up of St. Hyacin...,['Mary Fabyan Windeatt'],Biography & Autobiography,0,saint hyacinth of poland
9,Rising Sons and Daughters: Life Among Japan's ...,Wardell recalls his experience as a foreign st...,['Steven Wardell'],Social Science,0,rising sons and daughters life among japans ne...

--------------------------------------------------

📂 FILE: Books_rating.parquet
   Shape: 3,000,000 rows x 6 columns
   Columns: ['Id', 'Title', 'User_id', 'review/score', 'review/summary', 'review/text']

   Sample Data (First 10 rows):

,Id,Title,User_id,review/score,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,AVCGYZL8FQQTD,4.0,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,A30TK6U7DNS82R,5.0,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,A3UH4UZ4RSVO82,5.0,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,A2MVUWT453QH61,4.0,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,A22X4XUPKF66MR,4.0,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...
5,0826414346,Dr. Seuss: American Icon,A2F6NONFUDB6UK,4.0,One of America's greatest creative talents,"""Dr. Seuss: American Icon"" by Philip Nel is a ..."
6,0826414346,Dr. Seuss: American Icon,A14OJS0VWMOSWO,5.0,A memorably excellent survey of Dr. Seuss' man...,Theodor Seuss Giesel was best known as 'Dr. Se...
7,0826414346,Dr. Seuss: American Icon,A2RSSXTDZDUSH4,5.0,Academia At It's Best,When I recieved this book as a gift for Christ...
8,0826414346,Dr. Seuss: American Icon,A25MD5I2GUIW6W,5.0,And to think that I read it on the tram!,Trams (or any public transport) are not usuall...
9,0826414346,Dr. Seuss: American Icon,A3VA4XFS5WNJO3,4.0,Fascinating account of a genius at work,"As far as I am aware, this is the first book-l..."

--------------------------------------------------

📂 FILE: bx_books_metadata.parquet
   Shape: 271,064 rows x 4 columns
   Columns: ['ISBN', 'Book-Title', 'Book-Author', 'clean_title']

   Sample Data (First 10 rows):

,ISBN,Book-Title,Book-Author,clean_title
0,0195153448,Classical Mythology,Mark P. O. Morford,classical mythology
1,0002005018,Clara Callan,Richard Bruce Wright,clara callan
2,0060973129,Decision in Normandy,Carlo D'Este,decision in normandy
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,flu the story of the great influenza pandemic ...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,the mummies of urumchi
5,0399135782,The Kitchen God's Wife,Amy Tan,the kitchen gods wife
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,what if the worlds foremost military historian...
7,0671870432,PLEADING GUILTY,Scott Turow,pleading guilty
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,under the black flag the romance and the reali...
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,where youll find me and other stories

--------------------------------------------------

📂 FILE: bx_ratings.parquet
   Shape: 1,149,780 rows x 3 columns
   Columns: ['User-ID', 'ISBN', 'Book-Rating']

   Sample Data (First 10 rows):

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
5   276733  2080674722            0
6   276736  3257224281            8
7   276737  0600570967            6
8   276744  038550120X            7
9   276745   342310538           10

--------------------------------------------------

📂 FILE: bx_users.parquet
   Shape: 278,858 rows x 3 columns
   Columns: ['User-ID', 'Location', 'Age']

   Sample Data (First 10 rows):

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN
5        6       santa monica, california, usa  61.0
6        7                 washington, dc, usa   NaN
7        8            timmins, ontario, canada   NaN
8        9          germantown, tennessee, usa   NaN
9       10          albacete, wisconsin, spain  26.0

--------------------------------------------------

📂 FILE: goodreads_book_id_map.parquet
   Shape: 2,360,650 rows x 2 columns
   Columns: ['book_id_csv', 'book_id']

   Sample Data (First 10 rows):

   book_id_csv   book_id
0            0  34684622
1            1  34536488
2            2  34017076
3            3     71730
4            4  30422361
5            5  33503613
6            6  33517540
7            7  34467031
8            8   6383669
9            9    486625

--------------------------------------------------

📂 FILE: goodreads_books_part_000.parquet
   Shape: 300,000 rows x 9 columns
   Columns: ['book_id', 'title', 'description', 'genres', 'average_rating', 'ratings_count', 'isbn', 'author_id', 'clean_title']

   Sample Data (First 10 rows):

,book_id,title,description,genres,average_rating,ratings_count,isbn,author_id,clean_title
0,5333265,W.C. Fields: A Life on Film,,"to-read, p, collection",4.00,3,0312853122,604031,wc fields a life on film
1,1333909,Good Harbor,"Anita Diamant's international bestseller ""The ...","to-read, fiction, currently-reading",3.23,10,0743509986,626222,good harbor
2,7327624,"The Unschooled Wizard (Sun Wolf and Starhawk, ...",Omnibus book club edition containing the Ladie...,"to-read, fantasy, fiction",4.03,140,,10333,the unschooled wizard
3,6066819,Best Friends Forever,Addie Downs and Valerie Adler were eight when ...,"to-read, chick-lit, currently-reading",3.49,51184,0743294297,9212,best friends forever
4,287140,Runic Astrology: Starcraft and Timekeeping in ...,,"to-read, runes, owned",3.40,15,0850308712,149918,runic astrology starcraft and timekeeping in t...
5,287141,The Aeneid for Boys and Girls,"Relates in vigorous prose the tale of Aeneas, ...","to-read, currently-reading, history",4.13,46,1599150603,3041852,the aeneid for boys and girls
6,378460,The Wanting of Levine,,"to-read, read-gave-away, read-pre-1990",4.38,12,0425040887,215594,the wanting of levine
7,6066812,All's Fairy in Love and War (Avalon: Web of Ma...,"To Kara's astonishment, she discovers that a p...","to-read, fantasy, owned",4.22,98,1934876569,19158,alls fairy in love and war
8,34883016,Playmaker: A Venom Series Novella,Secrets. Sometimes keeping them in confidence ...,"to-read, ibooks, favorite-authors",3.86,5,,5807700,playmaker a venom series novella
9,287149,The Devil's Notebook,"Wisdom, humor, and dark observations by the fo...","to-read, currently-reading, occult",3.81,986,0922915113,2983296,the devils notebook

--------------------------------------------------

📂 FILE: goodreads_user_id_map.parquet
   Shape: 876,145 rows x 2 columns
   Columns: ['user_id_csv', 'user_id']

   Sample Data (First 10 rows):

   user_id_csv                           user_id
0            0  8842281e1d1347389f2ab93d60773d4d
1            1  72fb0d0087d28c832f15776b0d936598
2            2  ab2923b738ea3082f5f3efcbbfacb218
3            3  d986f354a045ffb91234e4af4d1b12fd
4            4  7504b2aee1ecb5b2872d3da381c6c91e
5            5  f8a89075dc6de14857561522e729f82c
6            6  47d4a49ae9ee68ae78d891b3a259b695
7            7  704eb93a316aff687a93d5215882eb21
8            8  06316bec7a49286f1f98d5acce24f923
9            9  012515e5802b2e0f42915118c90fa04b

--------------------------------------------------

**Amazon:**
* ID; 
* Title; (connector between files 1 and 2) 
* User ID; 
* Review/score; 
* Review/summary; 
* Review/text; 
* Description; 
* Authors; 
* Categories; 
* RatingsCount; (not relevant since it's incorrect)
* clean_title

**Book Crossing:**
* ISBN; (connecting files 3 and 4)
* Title;
* Author;
* clean_title;
* User ID; (connecting file 5)
* Book-rating;
* Location reviewer;
* Age reviewer

**Goodreads:**
* Book ID;
* Title;
* Description;
* genres;
* average rating;
* ratings_count;
* ISBN;
* author_id;
* clean_title

**Unified structure per book:**

*   global_book_id: unique key (AMZ_123, BX_024....)
*   title & clean_title
*   author
*   metadata: object/dict containing: Description; Category/Genre/Platform origin; Base average ratings
*   reviews: list of dictionary objects maintaining individual reviews intact

In [6]:
def load_p(filename):
    return pd.read_parquet(os.path.join(data_path, filename))



print("Loading files...")
amz_reviews = load_p('Books_rating.parquet')
amz_meta = load_p('amazon_books_metadata.parquet')
bx_meta = load_p('bx_books_metadata.parquet')
bx_ratings = load_p('bx_ratings.parquet')
bx_users = load_p('bx_users.parquet')
gr_books = load_p('goodreads_books_part_000.parquet')
print("All files loaded successfully!\n" + "="*50)

Loading files...
All files loaded successfully!
==================================================

In [9]:
# -------------------------------------------------------------------
# 1. PROCESS STREAM A: AMAZON
# -------------------------------------------------------------------
print("Starting with Amazon:")

display(amz_reviews.head())
display(amz_meta.head())

Starting with Amazon:

,Id,Title,User_id,review/score,review/summary,review/text
0,1882931173,Its Only Art If Its Well Hung!,AVCGYZL8FQQTD,4.0,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...
1,0826414346,Dr. Seuss: American Icon,A30TK6U7DNS82R,5.0,Really Enjoyed It,I don't care much for Dr. Seuss but after read...
2,0826414346,Dr. Seuss: American Icon,A3UH4UZ4RSVO82,5.0,Essential for every personal and Public Library,"If people become the books they read and if ""t..."
3,0826414346,Dr. Seuss: American Icon,A2MVUWT453QH61,4.0,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D..."
4,0826414346,Dr. Seuss: American Icon,A22X4XUPKF66MR,4.0,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...

,Title,description,authors,categories,ratingsCount,clean_title
0,Its Only Art If Its Well Hung!,<NA>,['Julie Strain'],Comics & Graphic Novels,0,its only art if its well hung
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],Biography & Autobiography,0,dr seuss american icon
2,Wonderful Worship in Smaller Churches,This resource includes twelve principles in un...,['David R. Ray'],Religion,0,wonderful worship in smaller churches
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],Fiction,0,whispers of the wicked saints
4,"Nation Dance: Religion, Identity and Cultural ...",<NA>,['Edward Long'],<NA>,0,nation dance religion identity and cultural di...

In [13]:
print("\n--- Processing Amazon Stream ---")

# Standardize score scale 1-5 -> 0.0-1.0
amz_reviews['normalized_score'] = (amz_reviews['review/score'] - 1.0) / (5.0 - 1.0)

# Structure individual reviews as a dict
amz_reviews['review_dict'] = amz_reviews.apply(
    lambda row: {
        'user_id': str(row['User_id']),
        'original_score': row['review/score'],
        'normalized_score': row['normalized_score'],
        'summary': row['review/summary'],
        'text': row['review/text'],
        'user_demographics': None
    }, axis=1
)

display(amz_reviews.head())

--- Processing Amazon Stream ---

,Id,Title,User_id,review/score,review/summary,review/text,normalized_score,review_dict
0,1882931173,Its Only Art If Its Well Hung!,AVCGYZL8FQQTD,4.0,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...,0.75,"{'user_id': 'AVCGYZL8FQQTD', 'original_score':..."
1,0826414346,Dr. Seuss: American Icon,A30TK6U7DNS82R,5.0,Really Enjoyed It,I don't care much for Dr. Seuss but after read...,1.00,"{'user_id': 'A30TK6U7DNS82R', 'original_score'..."
2,0826414346,Dr. Seuss: American Icon,A3UH4UZ4RSVO82,5.0,Essential for every personal and Public Library,"If people become the books they read and if ""t...",1.00,"{'user_id': 'A3UH4UZ4RSVO82', 'original_score'..."
3,0826414346,Dr. Seuss: American Icon,A2MVUWT453QH61,4.0,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D...",0.75,"{'user_id': 'A2MVUWT453QH61', 'original_score'..."
4,0826414346,Dr. Seuss: American Icon,A22X4XUPKF66MR,4.0,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...,0.75,"{'user_id': 'A22X4XUPKF66MR', 'original_score'..."

In [27]:
# Aggregate reviews per book Title
amz_grouped = amz_reviews.groupby('Id').agg(
    Title=('Title', 'first'),
    review_count=('review/score', 'count'),
    reviews_list=('review_dict', list)
).reset_index()

display(amz_grouped.head())

,Id,Title,review_count,reviews_list
0,0001047604,Aurora Leigh,4,"[{'user_id': 'A8G9GETA2OLMZ', 'original_score'..."
1,0001047655,The Prodigal Daughter,74,"[{'user_id': 'A3U9ZB72H7QM2P', 'original_score..."
2,0001047736,Summer of the Danes,12,"[{'user_id': 'A9ETDX5K04DY', 'original_score':..."
3,0001047825,Potters Field Audio,14,"[{'user_id': 'A1RLYOPK16YXC1', 'original_score..."
4,0001047876,Life of Samuel Johnson,8,"[{'user_id': 'AU97X77SREQUR', 'original_score'..."

In [28]:
# Join with Metadata on Title
amz_merged = pd.merge(amz_meta, amz_grouped, on='Title', how='left')
print(f"Amazon Total Books: {len(amz_merged):,}")
print(f"Amazon Books with >= 5 reviews: {(amz_merged['review_count'] >= 5).sum():,}")

Amazon Total Books: 209,186
Amazon Books with >= 5 reviews: 75,972

In [30]:
amz_5plus = amz_merged[amz_merged['review_count'] >= 5].copy()
display(amz_5plus.head())
print(len(amz_5plus))

,Title,description,authors,categories,ratingsCount,clean_title,Id,review_count,reviews_list
1,Dr. Seuss: American Icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],Biography & Autobiography,0,dr seuss american icon,0826414346,9,"[{'user_id': 'A30TK6U7DNS82R', 'original_score..."
3,Whispers of the Wicked Saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],Fiction,0,whispers of the wicked saints,0595344550,32,"[{'user_id': 'A3Q12RK71N74LB', 'original_score..."
11,Dramatica for Screenwriters,Dramatica for Screenwriters by Armando Saldana...,['Armando Salda A-Mora'],Reference,0,dramatica for screenwriters,0918973031,10,"[{'user_id': 'A252PRC1XBMTQJ', 'original_score..."
13,Vector Quantization and Signal Compression (Th...,"Herb Caen, a popular columnist for the San Fra...","['Allen Gersho', 'Robert M. Gray']",Technology & Engineering,0,vector quantization and signal compression,0792391810,5,"[{'user_id': 'A1CHPTJILEAL74', 'original_score..."
16,The Ultimate Guide to Law School Admission: In...,This collection brings together a distinguishe...,['Fiona Cownie'],Law,0,the ultimate guide to law school admission ins...,0974289108,7,"[{'user_id': 'A1KZ0RDJZQSY4O', 'original_score..."

75972

In [35]:

# -------------------------------------------------------------------
# 2. PROCESS STREAM B: BOOK-CROSSING
# -------------------------------------------------------------------
print("\n--- Processing Book-Crossing Stream ---")

display(bx_meta.head())
print(len(bx_meta))
display(bx_ratings.head())
print(len(bx_ratings))
display(bx_users.head())
print(len(bx_users))

--- Processing Book-Crossing Stream ---

,ISBN,Book-Title,Book-Author,clean_title
0,0195153448,Classical Mythology,Mark P. O. Morford,classical mythology
1,0002005018,Clara Callan,Richard Bruce Wright,clara callan
2,0060973129,Decision in Normandy,Carlo D'Este,decision in normandy
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,flu the story of the great influenza pandemic ...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,the mummies of urumchi

271064

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

1149780

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

278858

In [36]:
# Merge ratings with demographics
bx_reviews_full = pd.merge(bx_ratings, bx_users, on='User-ID', how='left')

display(bx_reviews_full)

,User-ID,ISBN,Book-Rating,Location,Age
0,276725,034545104X,0,"tyler, texas, usa",NaN
1,276726,0155061224,5,"seattle, washington, usa",NaN
2,276727,0446520802,0,"h, new south wales, australia",16.0
3,276729,052165615X,3,"rijeka, n/a, croatia",16.0
4,276729,0521795028,6,"rijeka, n/a, croatia",16.0
...,...,...,...,...,...
1149775,276704,1563526298,9,"cedar park, texas, usa",NaN
1149776,276706,0679447156,0,"quebec, quebec, canada",18.0
1149777,276709,0515107662,10,"mannington, west virginia, usa",38.0
1149778,276721,0590442449,10,"providence, rhode island, usa",14.0
1149779,276723,05162443314,8,"san antonio, texas, usa",12.0

In [53]:
# Exclude implicit 0 ratings if desired (Optional: change to > 0 if you only want explicit ratings)
bx_explicit = bx_reviews_full[bx_reviews_full['Book-Rating'] > 0].copy()

# Clean ISBN text without adding or padding any characters.
# Keep digits and X, which is a valid ISBN-10 check character.
def clean_isbn(series):
    cleaned = (
        series.astype('string')
        .str.replace(r'[^0-9Xx]', '', regex=True)
        .str.upper()
    )
    return cleaned.mask(cleaned.eq('') | cleaned.str.fullmatch(r'0+'))

bx_explicit['ISBN'] = clean_isbn(bx_explicit['ISBN'])
bx_meta['ISBN'] = clean_isbn(bx_meta['ISBN'])

# Standardize score scale 1-10 -> 0.0-1.0
bx_explicit['normalized_score'] = (bx_explicit['Book-Rating'] - 1.0) / (10.0 - 1.0)

display(bx_explicit.head())

,User-ID,ISBN,Book-Rating,Location,Age,normalized_score
1,276726,0155061224,5,"seattle, washington, usa",NaN,0.444444
3,276729,052165615X,3,"rijeka, n/a, croatia",16.0,0.222222
4,276729,0521795028,6,"rijeka, n/a, croatia",16.0,0.555556
6,276736,3257224281,8,"salzburg, salzburg, austria",NaN,0.777778
7,276737,0600570967,6,"sydney, new south wales, australia",14.0,0.555556

In [55]:
# Structure individual review dict
bx_explicit['review_dict'] = bx_explicit.apply(
    lambda row: {
        'user_id': str(row['User-ID']),
        'original_score': row['Book-Rating'],
        'normalized_score': row['normalized_score'],
        'summary': None,
        'text': None,
        'user_demographics': {
            'age': row['Age'] if pd.notnull(row['Age']) else None,
            'location': row['Location'] if pd.notnull(row['Location']) else None
        }
    }, axis=1
)

display(bx_explicit.head())

,User-ID,ISBN,Book-Rating,Location,Age,normalized_score,review_dict
1,276726,0155061224,5,"seattle, washington, usa",NaN,0.444444,"{'user_id': '276726', 'original_score': 5, 'no..."
3,276729,052165615X,3,"rijeka, n/a, croatia",16.0,0.222222,"{'user_id': '276729', 'original_score': 3, 'no..."
4,276729,0521795028,6,"rijeka, n/a, croatia",16.0,0.555556,"{'user_id': '276729', 'original_score': 6, 'no..."
6,276736,3257224281,8,"salzburg, salzburg, austria",NaN,0.777778,"{'user_id': '276736', 'original_score': 8, 'no..."
7,276737,0600570967,6,"sydney, new south wales, australia",14.0,0.555556,"{'user_id': '276737', 'original_score': 6, 'no..."

In [56]:
# Aggregate reviews per ISBN
bx_grouped = bx_explicit.groupby('ISBN').agg(
    review_count=('Book-Rating', 'count'),
    reviews_list=('review_dict', list)
).reset_index()

display(bx_grouped.head())

,ISBN,review_count,reviews_list
0,0000000000090,1,"[{'user_id': '35997', 'original_score': 10, 'n..."
1,0000000010,1,"[{'user_id': '29553', 'original_score': 8, 'no..."
2,0000000016964,1,"[{'user_id': '36316', 'original_score': 7, 'no..."
3,0000000020,1,"[{'user_id': '29553', 'original_score': 9, 'no..."
4,0000000022057,1,"[{'user_id': '244923', 'original_score': 3, 'n..."

In [59]:
# Join with Metadata on ISBN
bx_merged = pd.merge(bx_meta, bx_grouped, on='ISBN', how='left')
print(f"Book-Crossing Total Books: {len(bx_merged):,}")
print(f"Book-Crossing Books with >= 5 reviews: {(bx_merged['review_count'] >= 5).sum():,}")

Book-Crossing Total Books: 271,064
Book-Crossing Books with >= 5 reviews: 13,816

In [60]:
bx_5plus = bx_merged[bx_merged['review_count'] >= 5].copy()
display(bx_5plus.head())
print(len(bx_5plus))

,ISBN,Book-Title,Book-Author,clean_title,review_count,reviews_list
1,0002005018,Clara Callan,Richard Bruce Wright,clara callan,9.0,"[{'user_id': '8', 'original_score': 5, 'normal..."
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,flu the story of the great influenza pandemic ...,6.0,"[{'user_id': '35704', 'original_score': 6, 'no..."
5,0399135782,The Kitchen God's Wife,Amy Tan,the kitchen gods wife,17.0,"[{'user_id': '11676', 'original_score': 9, 'no..."
18,0440234743,The Testament,John Grisham,the testament,169.0,"[{'user_id': '3329', 'original_score': 8, 'nor..."
19,0452264464,Beloved (Plume Contemporary Fiction),Toni Morrison,beloved,79.0,"[{'user_id': '9', 'original_score': 6, 'normal..."

13816

In [62]:

# -------------------------------------------------------------------
# 3. PROCESS STREAM C: GOODREADS
# -------------------------------------------------------------------
print("\n--- Goodreads Stream ---")
print(f"Goodreads Metadata Books: {len(gr_books):,}")
display(gr_books.head())

--- Goodreads Stream ---
Goodreads Metadata Books: 300,000

,book_id,title,description,genres,average_rating,ratings_count,isbn,author_id,clean_title
0,5333265,W.C. Fields: A Life on Film,,"to-read, p, collection",4.00,3,0312853122,604031,wc fields a life on film
1,1333909,Good Harbor,"Anita Diamant's international bestseller ""The ...","to-read, fiction, currently-reading",3.23,10,0743509986,626222,good harbor
2,7327624,"The Unschooled Wizard (Sun Wolf and Starhawk, ...",Omnibus book club edition containing the Ladie...,"to-read, fantasy, fiction",4.03,140,,10333,the unschooled wizard
3,6066819,Best Friends Forever,Addie Downs and Valerie Adler were eight when ...,"to-read, chick-lit, currently-reading",3.49,51184,0743294297,9212,best friends forever
4,287140,Runic Astrology: Starcraft and Timekeeping in ...,,"to-read, runes, owned",3.40,15,0850308712,149918,runic astrology starcraft and timekeeping in t...

In [66]:
gr_5plus = gr_books[gr_books['ratings_count'] >= 5].copy()
print(len(gr_5plus))

236737

In [77]:
# Standardize all three sources to one common schema.
# Reviews_List contains review dictionaries; Average_Normalized_Rating is always on a 0-1 scale.
common_columns = [
    'Title',
    'Clean_Title',
    'Description',
    'Authors',
    'Category/Genre',
    'ISBN/ID',
    'Book ID',
    'Review_Count',
    'Reviews_List',
    'Average_Normalized_Rating'
]


def average_review_score(reviews):
    """Return the mean normalized score from a list of review dictionaries."""
    if not isinstance(reviews, list):
        return np.nan

    scores = [
        review.get('normalized_score')
        for review in reviews
        if isinstance(review, dict) and pd.notna(review.get('normalized_score'))
    ]
    return np.mean(scores) if scores else np.nan


# Rebuild the filtered source dataframes so this cell can be rerun safely.
amz_source = amz_merged[amz_merged['review_count'] >= 5].copy()
bx_source = bx_merged[bx_merged['review_count'] >= 5].copy()
gr_source = gr_books[gr_books['ratings_count'] >= 5].copy()
goodreads_rating = pd.to_numeric(gr_source['average_rating'], errors='coerce')
goodreads_normalized_rating = ((goodreads_rating - 1.0) / 4.0).where(
    goodreads_rating.between(1.0, 5.0)
)

amz_standardized = pd.DataFrame({
    'Title': amz_source['Title'],
    'Clean_Title': amz_source['clean_title'],
    'Description': amz_source['description'],
    'Authors': amz_source['authors'],
    'Category/Genre': amz_source['categories'],
    'ISBN/ID': None,
    'Book ID': 'AMZ_' + amz_source['Id'].astype('string'),
    'Review_Count': amz_source['review_count'],
    'Reviews_List': amz_source['reviews_list'],
    'Average_Normalized_Rating': amz_source['reviews_list'].apply(average_review_score)
})

bx_standardized = pd.DataFrame({
    'Title': bx_source['Book-Title'],
    'Clean_Title': bx_source['clean_title'],
    'Description': None,
    'Authors': bx_source['Book-Author'],
    'Category/Genre': None,
    'ISBN/ID': bx_source['ISBN'],
    'Book ID': 'BX_' + pd.Series(range(len(bx_source)), index=bx_source.index).astype('string').str.zfill(7),
    'Review_Count': bx_source['review_count'],
    'Reviews_List': bx_source['reviews_list'],
    'Average_Normalized_Rating': bx_source['reviews_list'].apply(average_review_score)
})

# Goodreads average_rating is on a 1-5 scale; invalid values become missing.
gr_standardized = pd.DataFrame({
    'Title': gr_source['title'],
    'Clean_Title': gr_source['clean_title'],
    'Description': gr_source['description'],
    'Authors': None,
    'Category/Genre': gr_source['genres'],
    'ISBN/ID': gr_source['isbn'],
    'Book ID': 'GR_' + gr_source['book_id'].astype('string'),
    'Review_Count': gr_source['ratings_count'],
    'Reviews_List': None,
    'Average_Normalized_Rating': goodreads_normalized_rating
})

amz_5plus = amz_standardized[common_columns]
bx_5plus = bx_standardized[common_columns]
gr_5plus = gr_standardized[common_columns]

# The three dataframes now have identical columns and can be concatenated.
all_books = pd.concat([amz_5plus, bx_5plus, gr_5plus], ignore_index=True)

print('Common columns:', list(all_books.columns))
print(f'Amazon: {len(amz_5plus):,} | Book-Crossing: {len(bx_5plus):,} | Goodreads: {len(gr_5plus):,}')
print(f'Combined: {len(all_books):,}')
print('\nNormalized rating ranges:')
print(all_books['Average_Normalized_Rating'].describe()[['min', 'max', 'mean']])
display(all_books.head())

C:\Users\Gebruiker\AppData\Local\Temp\ipykernel_28144\859360002.py:84: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_books = pd.concat([amz_5plus, bx_5plus, gr_5plus], ignore_index=True)

Common columns: ['Title', 'Clean_Title', 'Description', 'Authors', 'Category/Genre', 'ISBN/ID', 'Book ID', 'Review_Count', 'Reviews_List', 'Average_Normalized_Rating']
Amazon: 75,972 | Book-Crossing: 13,816 | Goodreads: 236,737
Combined: 326,525

Normalized rating ranges:
min     0.000000
max     1.000000
mean    0.741667
Name: Average_Normalized_Rating, dtype: float64

,Title,Clean_Title,Description,Authors,Category/Genre,ISBN/ID,Book ID,Review_Count,Reviews_List,Average_Normalized_Rating
0,Dr. Seuss: American Icon,dr seuss american icon,Philip Nel takes a fascinating look into the k...,['Philip Nel'],Biography & Autobiography,None,AMZ_0826414346,9.0,"[{'user_id': 'A30TK6U7DNS82R', 'original_score...",0.888889
1,Whispers of the Wicked Saints,whispers of the wicked saints,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],Fiction,None,AMZ_0595344550,32.0,"[{'user_id': 'A3Q12RK71N74LB', 'original_score...",0.679688
2,Dramatica for Screenwriters,dramatica for screenwriters,Dramatica for Screenwriters by Armando Saldana...,['Armando Salda A-Mora'],Reference,None,AMZ_0918973031,10.0,"[{'user_id': 'A252PRC1XBMTQJ', 'original_score...",0.925000
3,Vector Quantization and Signal Compression (Th...,vector quantization and signal compression,"Herb Caen, a popular columnist for the San Fra...","['Allen Gersho', 'Robert M. Gray']",Technology & Engineering,None,AMZ_0792391810,5.0,"[{'user_id': 'A1CHPTJILEAL74', 'original_score...",0.850000
4,The Ultimate Guide to Law School Admission: In...,the ultimate guide to law school admission ins...,This collection brings together a distinguishe...,['Fiona Cownie'],Law,None,AMZ_0974289108,7.0,"[{'user_id': 'A1KZ0RDJZQSY4O', 'original_score...",0.642857

In [81]:
# Save the combined dataset as a JSON array of book records.
# Write one record at a time to avoid loading the complete JSON document into memory.
import json

json_path = Path('all_books.json')
temp_json_path = json_path.with_suffix('.json.tmp')


def make_json_safe(value):
    if isinstance(value, dict):
        return {key: make_json_safe(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [make_json_safe(item) for item in value]
    if isinstance(value, np.generic):
        return make_json_safe(value.item())
    if value is None:
        return None

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    return value


with temp_json_path.open('w', encoding='utf-8') as output_file:
    output_file.write('[\n')

    for row_number, row in enumerate(all_books.itertuples(index=False, name=None)):
        if row_number:
            output_file.write(',\n')

        record = dict(zip(all_books.columns, row))
        json.dump(
            make_json_safe(record),
            output_file,
            ensure_ascii=False,
            separators=(',', ':')
        )

    output_file.write('\n]\n')

temp_json_path.replace(json_path)
print(f'Saved {len(all_books):,} records to {json_path.resolve()}')

Saved 326,525 records to C:\Users\Gebruiker\Documents\AI engineer course - Hebrew University\book_recommendations_project\all_books.json